### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by vhouchouas** [Zero-Waste-Paris/membership-scripts#4]
https://github.com/Zero-Waste-Paris/membership-scripts/blob/3de4dce1f186970a1c52d9e724fd9dfbc7b76d7f/LICENSE.txt#L189

Maybe something like:

```Copyright 2022 Zero Waste Paris ```

**Comment by gturri** [comment]
This file was removed by commit https://github.com/Zero-Waste-Paris/membership-scripts/commit/67f69cc5add6fee5c80cd9d51710a035c4f14c59 and the copyright thing is now on each source file.
Is it ok with you if we close this issue @vhouchouas?
(I'm realizing that I'm totally not familiar with how licensing is supposed to be applied so it's completely possible that I missed something...)

**Comment by vhouchouas** [comment]
Ok !
